### PR TITLE
Fix background

### PR DESCRIPTION
**Pull request by davidchiles**
This is an alternative to https://github.com/swisspol/GCDWebServer/pull/292. 

I didn't have luck with the previous restart code but when I stopped and started the server everything seemed to work fine.

### CODE REVIEW

**Comment by macrozone** [comment]
Fixes one of my issues in a meteor cordova app.

**Comment by macrozone** [comment]
@swisspol any update on this? meteor would also benefit from this change.

**Comment by Nauzer** [comment]
+1 👍

**Comment by macrozone** [comment]
would be cool if this project here would merge or at least comment all these pending PRs, because the meteor community relies on it. :-/

**Pull request closed without merging**
