### PR TITLE
Add .swift-version file to be used by Cocoapods 1.1.0 and up

### PR DESCRIPTION
**Pull request by kdbertel**
Per documentation [here](http://blog.cocoapods.org/CocoaPods-1.1.0/), Cocoapods 1.1.0 introduced a `.swift-version` file that is used by Cocoapods to indicate what version of Swift is used in the project.

### CODE REVIEW

**Comment by swisspol** [comment]
Unless I'm missing something, this is not needed anyway since GCDWebServer is written in Obj-C not Swift.

**Comment by kdbertel** [comment]
My recollection when I authored this months ago is that Cocoapods complains and Xcode cannot build the project file, even if the library is technically all Objective-C.

**Comment by swisspol** [comment]
Docs says that it defaults to Swift 3.0 if the file doesn't exist, so no matter what they must have fixed their issue.

**Comment by kdbertel** [comment]
Fair. If it crops up again I'll file another issue/PR with more details.

**Pull request closed without merging**
