### PR TITLE
Fixed repeated invocation of block for GCDWebServerStreamedResponse

### PR DESCRIPTION
**Pull request by KJTsanaktsidis**
When attempting to use the GCDWebServerStreamedResponse as described
in the README, repeatedly invoking the GCDWebServerBodyReaderCompletionBlock
to signal the readiness of more data, a number of bad things happen:

-The read loop in GCDWebServerConnection writeBodyWithCompletionBlock:
repeatedly invokes the body reader completion block attached to the
streamed response object (because of a recursive call to
writeBodyWithCompletionBlock).
I.e. every time the BodyReaderCompletionBlock is called by the
asyncStreamBlock, the asyncStreamBlock is invoked again.

-This leads to a large number of "broken pipe" warnings in the console
on iOS8, at least. On a larger project it with many requests it would
reliably result in an EXC_BAD_ACCESS, but I have not been able to reproduce
this on a small project.

This can be demonstrated by creating a simple GCDWebServer that does the following:

````objective-c
    self->_server = [[GCDWebServer alloc] init];
    dispatch_time_t half_second = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC));
    
    [self->_server
        addDefaultHandlerForMethod:@"GET"
        requestClass:[GCDWebServerDataRequest class]
        asyncProcessBlock:^(GCDWebServerRequest *request, GCDWebServerCompletionBlock completionBlock) {
            
            //Wait half a second before sending headers
            dispatch_after(half_second, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                
                GCDWebServerStreamedResponse* res =
                    [[GCDWebServerStreamedResponse alloc]
                        initWithContentType:@"text/plain"
                        asyncStreamBlock:^(GCDWebServerBodyReaderCompletionBlock dataCompletionBlock) {
                            
                            NSLog(@"Sending abcdefg");
                            dataCompletionBlock([@"abcdefg" dataUsingEncoding:NSUTF8StringEncoding], nil);
                            
                            dispatch_after(half_second, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                                
                                NSLog(@"Sending hijklmnop");
                                dataCompletionBlock([@"hijklmnop" dataUsingEncoding:NSUTF8StringEncoding], nil);
                                dataCompletionBlock([[NSData alloc] init], nil);
                                NSLog(@"ended");
                            });
                    }];
                    completionBlock(res);
            });
    }];
    
    return self;
````
If you make a single request to this web server, you get the following output:
````
[DEBUG] Did open IPv4 listening socket 7
[DEBUG] Did open IPv6 listening socket 8
[INFO] GCDWebServer started on port 10001 and reachable at http://192.168.0.14:10001/
[DEBUG] Did open connection on socket 13
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 204 bytes on socket 13
[DEBUG] Connection on socket 13 preflighting request "GET /something.txt" with 204 bytes body
[DEBUG] Connection on socket 13 processing request "GET /something.txt" with 204 bytes body
[DEBUG] Connection sent 176 bytes on socket 13
2015-01-02 17:57:18.210 gcd_test[4313:89119] Sending abcdefg
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.212 gcd_test[4313:89118] Sending hijklmnop
2015-01-02 17:57:18.212 gcd_test[4313:89118] ended
2015-01-02 17:57:18.212 gcd_test[4313:89119] Sending abcdefg
[DEBUG] Connection sent 14 bytes on socket 13
[DEBUG] Connection sent 5 bytes on socket 13
2015-01-02 17:57:18.212 gcd_test[4313:89118] Sending hijklmnop
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.212 gcd_test[4313:89133] Sending abcdefg
2015-01-02 17:57:18.212 gcd_test[4313:89138] Sending abcdefg
2015-01-02 17:57:18.212 gcd_test[4313:89118] ended
2015-01-02 17:57:18.212 gcd_test[4313:89133] Sending hijklmnop
[DEBUG] Connection sent 5 bytes on socket 13
[DEBUG] Connection sent 14 bytes on socket 13
2015-01-02 17:57:18.212 gcd_test[4313:89129] Sending hijklmnop
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89133] ended
2015-01-02 17:57:18.213 gcd_test[4313:89139] Sending abcdefg
2015-01-02 17:57:18.213 gcd_test[4313:89129] ended
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89138] Sending abcdefg
2015-01-02 17:57:18.213 gcd_test[4313:89118] Sending abcdefg
[DEBUG] Connection sent 14 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89139] Sending hijklmnop
2015-01-02 17:57:18.213 gcd_test[4313:89138] Sending hijklmnop
[DEBUG] Connection sent 5 bytes on socket 13
[DEBUG] Connection sent 14 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89118] Sending abcdefg
[DEBUG] Connection sent 5 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89139] ended
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89133] Sending abcdefg
2015-01-02 17:57:18.213 gcd_test[4313:89138] ended
2015-01-02 17:57:18.213 gcd_test[4313:89118] Sending abcdefg
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89139] Sending hijklmnop
[DEBUG] Connection sent 12 bytes on socket 13
[DEBUG] Connection sent 14 bytes on socket 13
2015-01-02 17:57:18.213 gcd_test[4313:89133] Sending hijklmnop
2015-01-02 17:57:18.213 gcd_test[4313:89129] Sending hijklmnop
[DEBUG] Connection sent 5 bytes on socket 13
[DEBUG] Connection sent 14 bytes on socket 13
2015-01-02 17:57:18.214 gcd_test[4313:89141] Sending abcdefg
[DEBUG] Connection sent 5 bytes on socket 13
2015-01-02 17:57:18.214 gcd_test[4313:89118] Sending abcdefg
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.214 gcd_test[4313:89139] ended
[DEBUG] Connection sent 12 bytes on socket 13
2015-01-02 17:57:18.214 gcd_test[4313:89119] Sending abcdefg
2015-01-02 17:57:18.214 gcd_test[4313:89133] ended
2015-01-02 17:57:18.214 gcd_test[4313:89138] Sending abcdefg
2015-01-02 17:57:18.214 gcd_test[4313:89129] ended
2015-01-02 17:57:18.214 gcd_test[4313:89143] Sending hijklmnop
2015-01-02 17:57:18.214 gcd_test[4313:89142] Sending abcdefg
2015-01-02 17:57:18.214 gcd_test[4313:89118] Sending hijklmnop
2015-01-02 17:57:18.214 gcd_test[4313:89139] Sending hijklmnop
2015-01-02 17:57:18.214 gcd_test[4313:89144] Sending abcdefg
2015-01-02 17:57:18.214 gcd_test[4313:89133] Sending hijklmnop
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89142] Sending hijklmnop
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89129] Sending hijklmnop
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89143] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89118] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89133] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89144] Sending hijklmnop
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89139] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.214 gcd_test[4313:89117] Got alphabet: abcdefghijklmnop
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.215 gcd_test[4313:89129] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.215 gcd_test[4313:89142] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
2015-01-02 17:57:18.215 gcd_test[4313:89144] ended
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[ERROR] Error while writing to socket 13: Broken pipe (32)
[DEBUG] Did close connection on socket 13
[VERBOSE] [::1c1e:cd17:0:0:10001] ::5c3:21e:4083:b00:52503 200 "GET /something.txt" (204 | 398)
[DEBUG] Did disconnect
[DEBUG] Did end background task
````
The asyncStreamBlock is called many times even though just one request was made. In this case, the full response
is written to the socket before the handler is called a second time, so the worst thing that happens is that a closed socket
is written to, but it's possible for the response to become garbage (by having had the same data written to it multiple times),
and in a larger project of mine, this problem would reliably cause an EXC_BAD_ACCESS in the GCDWebServerConnection.

There is a full reproduction project here: https://github.com/KJTsanaktsidis/GCDWebServer-Stream-Issue

This problem is fundamentially due to the differences in the sync and async
body model. For synchronous responses, they are expected to return some
data from performDataReadWithCompletion:, and the connection repeatedly
calls this method until there is no data left.

For asynchronous responses, the user of the library can happily invoke
the BodyReaderCompletionBlock multiple times until they are done; there is
no need for the connection to have a loop driving this process.

This commit addresses this issue by only repeatedly calling
performDataReadWithCompletion: for synchronous response types

### CODE REVIEW

**Comment by swisspol** [comment]
Thanks for the extensive issue report, I'll look into this. Unfortunately this is not the right fix as this is adding a special case for `GCDWebServerStreamedResponse` inside the core of GCDWebServer.

**Comment by KJTsanaktsidis** [comment]
I kind of agree this isn't the nicest way to go about this, just wanted to get the ball rolling. Can you suggest what the right way to tackle this might be?

**Comment by KJTsanaktsidis** [comment]
I have changed the fix to work at the GCDWebServerStreamedResponse level now. It simply ensures that the asyncProgressBlock is not called multiple times. I feel like this is just hacking over the connection manager making a call it should know not to make, but at least it doesn't poke at the guts of things and still doesn't break any internal API.

**Comment by swisspol** [comment]
I added a test case in the Mac test tool of the Xcode project: 3618dcac7e906e8334419b2c262a755cde0f8666

Try running the tool with `-mode asyncResponse2` then do a `GET` on `/` like this:
```
$ curl -v http://localhost:8080
* Rebuilt URL to: http://localhost:8080/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Transfer-Encoding: chunked
< Content-Type: text/plain
< Connection: Close
* Server GCDWebServer is not blacklisted
< Server: GCDWebServer
< Date: Fri, 02 Jan 2015 17:42:00 GMT
< 
10
9
8
7
6
5
4
3
2
1
* Closing connection 0
```

This appears to work fine, so let me know what you find that differs in your use case.

**Comment by KJTsanaktsidis** [comment]
Yes, this works as expected, because you have designed your asyncStreamBlock added in 3618dca to be called multiple times from the web server, calling the completion callback once per invocation.

However, the documentation in the readme for the "advanced asynchronous version" implies that your asyncStreamBlock gets called once, and can call the completion callback as many times as it likes.

IMO, the latter behaviour leads to clearer code for consumers of the library, because there is no need to manage the current response state in the asyncStreamBlock (i.e. what you have done with your countDown variable).

In any case, either the code or the documentation here needs to be fixed!

**Comment by swisspol** [comment]
Sorry, I don't understand what you are saying: you can indeed call `GCDWebServerBodyReaderCompletionBlock` as many times as you want and finalize the response with a last calling passing an empty NSData. That's what the example in the "Advanced asynchronous version" in the README does and that's what the sample code does as well.

**Comment by KJTsanaktsidis** [comment]
The point I'm trying to make is, the code provided in the README will produce console output similar to that I posted above- each time the asyncStreamBlock calls the GCDWebServerBodyReaderCompletionBlock, the underlying GCDWebServerConnection will call the asyncStreamBlock again. This leads to the asyncStreamBlock being called multiple times in response to the same request, leading to

-warnings about writing the same data again to a closed socket
-the repeated invocation of a library user's block which may cause side effects

Again, the difference between the example in the readme and your test code in 3618dca is that the former calles GCDWebServerBodyReaderCompletionBlock multiple times per invocation of the asyncStreamBlock, whereas the latter calls the BodyReaderCompletionBlock only once per invocation of the asyncStreamBlock.

**Comment by swisspol** [comment]
You can do a number of things with GCDWebServer:

1) Return synchronously a "static" response: https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m#L216

2) Return synchronously a "streaming" response that blocks GCDWebServer until data is available: https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m#L319

3) Return synchronously a "streaming" response that calls back (one or more times) to GCDWebServer when the data is available: https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m#L337

4) Return asynchronously a "static" response: https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m#L362

5) Return synchronously a "streaming" response that blocks GCDWebServer until data is available: (no test case)

6) Return asynchronously a "streaming" response that calls back (one or more times) to GCDWebServer when the data is available: https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m#L362

The README is case 3. You can copy paste that code in the Mac test tool and see that it works:
```
$ curl -v http://localhost:8080
* Rebuilt URL to: http://localhost:8080/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Transfer-Encoding: chunked
< Content-Type: text/html
< Connection: Close
* Server GCDWebServer is not blacklisted
< Server: GCDWebServer
< Date: Sat, 03 Jan 2015 02:10:15 GMT
< 
* Closing connection 0
<html><body><p>Hello<html><body><p>HelloWorld</p></body></html>
```

**Comment by KJTsanaktsidis** [comment]
^it doesn't work at all; I would expect it to print out `<html><body><p>HelloWorld</p></body></html>`, but in fact the output you pasted above is `<html><body><p>Hello<html><body><p>HelloWorld</p></body></html>`.

The first part of the asyncStreamBlock that prints out `</html></body></p>Hello` has actually run twice, and you can see that this data has actually appeared in the output twice.

**Comment by swisspol** [comment]
AAAAHHH I see... yes indeed, that behavior of calling the callback multiple times within the same block is not supported and wasn't meant to. It's more like a deferred return model. I cleaned up the docs. Thanks!

If you want that other behavior to be considered, feel free to create an issue for it. However the fixes you suggested would be backward incompatible. This would need to be another async model on top of the existing ones.

**Comment by KJTsanaktsidis** [comment]
I think the best way to tackle this is a different response type with a different API, something like GCDWebServerPushStreamingResponse. I'll throw an implementation together and you can see what you think.

**Comment by swisspol** [comment]
Before even looking at any code, I'm not sure this "push" model is a good idea to have in GCDWebServer.

The server instance is the one which knows best when it's time to ask for more data from the API client based on what the HTTP client itself reads. GCDWebServer is built on GCD and dispatch write / read for this exact purpose: optimizing the network traffic from the kernel to the app. The entire architecture is really based around the server requesting data when needed. Starting to have API clients "force" push data into the server instance will just result in things more likely blocking there and add complexity to the code.

Anyway, if this is something you would like to see, the best place to discuss this is a separate issue. Provide as much info as possible regarding what you effectively need this.

**Pull request closed without merging**
