### PR TITLE
Fixed CocoaLumberjack deps

### PR DESCRIPTION
**Pull request by anton-matosov**
Core:
```
pod 'GCDWebServer/CocoaLumberjack'
```

WebDAV:
```
pod 'GCDWebServer/WebDAV/CocoaLumberjack'
```

WebUploader
```
pod 'GCDWebServer/WebUploader/CocoaLumberjack'
```

### CODE REVIEW

**Comment by swisspol** [comment]
Seems clean thanks

**Comment by anton-matosov** [comment]
@swisspol can you please push this fix to pods trunk so I can add CocoaLumberjack subspec dependency in my podspec?

**Comment by swisspol** [comment]
3.3.1 is out.

**Comment by anton-matosov** [comment]
Thank you. Appreciate that

**Pull request merged**
