### PR TITLE
Add handleException:forRequest: in GCDWebServerConnection for subclassing

### PR DESCRIPTION
**Pull request by levey**

### CODE REVIEW

**Comment by swisspol** [comment]
What problem are you exactly trying to solve?

Exceptions are not part of the typical program flow in ObjC: it's not like Java or C#. Exceptions are reserved to programmer errors. Based on this, the way GCDWebServer deals with exceptions today is not going to change.

**Comment by levey** [comment]
Currently if exception happened in request handler will be omitted, client will get status 0, it not the correct part, I think better to let user decide to handle the exception, by default, this PR returns 500 to client, indicating that's server side error.

**Comment by swisspol** [comment]
There's only 1 location in the entire project that attempts to deal with exceptions:
```
@try {
    _handler.asyncProcessBlock(request, [completion copy]);
  }
  @catch (NSException* exception) {
    GWS_LOG_EXCEPTION(exception);
  }
```

But I just realized that since GCDWebServer added async support in version 3, this won't even work correctly anymore, since `asyncProcessBlock()` is non-blocking: the process block could throw at any time later and the exception would not be caught. I just therefore just removed that exception handling code: 5834770e083cc4e72c7fa13f9c3f0d5accad89da.

In your case, if you really want to handle exceptions, do it within your handler and prevent them to propagate to GCDWebServer.

**Comment by levey** [comment]
I thought most exception happened in user created request handlers, and this processRequest:completion: is the common place to handle exception. 
Otherwise, user have to use try-catch block in every entry of api request handlers, this is really unnecessary.
And I can catch some exceptions like fatal error in the @try-catch block in asyncProcessBlock()

**Comment by swisspol** [comment]
In practice, the vast vast majority of Obj-C code out there does not use exceptions. They are only used by the OS frameworks to report some programmer errors, not runtime errors or provide any sort of error reporting. Obj-C is very different from other languages that support exceptions.

If you have to deal with exceptions in your Obj-C code, it means you're most likely doing something wrong...

**Comment by levey** [comment]
My target is catching programmer errors in api request handler... like other web frameworks, if programmer errors occurred, server will return 50x error.

**Pull request closed without merging**
