### PR TITLE
Ensure that the server does not start with nil options #147

### PR DESCRIPTION
**Pull request by davidchiles**

### CODE REVIEW

**Comment by swisspol** [comment]
What's the test case that makes this check required? The public API does already check or am I missing something:
```
- (BOOL)startWithOptions:(NSDictionary*)options error:(NSError**)error {
  if (_options == nil) {
```

**Comment by davidchiles** [comment]
We created a small sample app where you can start the server with nil options. 

https://github.com/ChatSecure/IOCipher-ObjC/blob/master/Example/IOCipherServer/ViewController.m#L114

In this example we were also able to add handlers after the server was started because ```_options``` is ```nil``` and therefore seems like it's not running to the checks.

**Comment by swisspol** [comment]
Ah I see, it was checking for `_options` not `options`. I fixed it in 9c33c83. Thanks!

**Comment by swisspol** [comment]
BTW you're not using `-startWithOptions:error:` property in your code: you must check for the returned value.

**Comment by davidchiles** [comment]
Maybe the readme and example projects need check the returned value too 😊

**Comment by swisspol** [comment]
It's not the same. These examples skip over error handling as that's not the point. However, if you want to do error handling like I assume you do in your code, then, like the docs explain, you must check the return value and not just that `error` has changed (which wouldn't be the proper pattern and could generate false positives):
https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.h#L331

**Pull request closed without merging**
